Raise a ValueError for undefined hosts
The method `createTargetCommand` needs to raise an error if it cannot
determine the hosts for the target. Just `pass`ing here leads to a

  UnboundLocalError: local variable 'hosts' referenced before assignment

when neither `hosts` nor `asset_hosts` are present in the kwargs.